# =====================================================================
# Reverse Proxy configurations
# =====================================================================

server:
  port: "8080"
services:
  - name: "bit-driver-location-svc"
    target: "localhost:8082"
    strategy: "check-auth"
    listen: "/location-svc/"
    path: "/nearest-driver-location"

  - name: "bit-driver-match-svc"
    target: "localhost:8083"
    strategy: "check-auth"
    listen: "/match-svc"
    path: "/find-nearest"